version: "3.0"
services:
    tse_padron_api_dev:
      container_name: tse_consultapadron_api_dev
      build:
        context: .
      image: tse_consultapadron_api_dev 
      ports:
       - "5001:5001"
      restart: unless-stopped
      networks:
      - default
      environment:
        - BD_URL=jdbc:oracle:thin:@//100.100.1.96:1521/TSEP3
        - BD_USER=WSRNPCONSULTA
        - BD_PASSWORD=W5RN7QR7
        - SSO_API_URL=http://192.168.79.67:9763
        - FILES_API_URL=http://192.168.79.66:3005
        - CERTIFICATE_API_URL=http://192.168.79.66:3003
        - CERTIFICATE_SIGN_URL= http://192.168.79.66:5000
        - REQUEST_ROUTE=certificado_trabajador_solicitudes_dev
        - TZ=America/Guatemala
        
      volumes:
         - /etc/localtime:/etc/localtime:ro
         - /etc/timezone:/etc/timezone:ro
networks:
  default:
    external:
      name: tse_internal