version: "3.0"
services:
    tse_padron_api_prod:
      container_name: tse_padron_api_prod
      build:
        context: .
      image: tse_padron_api_prod
      restart: unless-stopped
      ports:
      - "5005:8099"
      networks:
      - default
      environment:
        - BD_URL=jdbc:oracle:thin:@//192.168.79.134:1521/WEBCP
        - BD_USER=WEBCERTIFICACION
        - BD_PASSWORD=TDtu5#43A
      
networks:
  default:
    external:
      name: tse_internal
